//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class APTRANM
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public string CLCODE { get; set; }
        public Nullable<short> CLADDRID { get; set; }
        public string INVNO { get; set; }
        public Nullable<System.DateTime> INVDATE { get; set; }
        public Nullable<System.DateTime> INVDUE { get; set; }
        public System.DateTime ENTDATE { get; set; }
        public string TRTYPE { get; set; }
        public string TRDESC { get; set; }
        public string CURRCODE { get; set; }
        public decimal TRAMT { get; set; }
        public string TRSIGN { get; set; }
        public decimal TRSAMT { get; set; }
        public decimal TROS { get; set; }
        public string APPTYPE { get; set; }
        public string APPNO { get; set; }
        public Nullable<int> APPID { get; set; }
        public decimal APPAMT { get; set; }
        public string REM { get; set; }
        public string COMPLETE { get; set; }
        public System.DateTime COMPLETED { get; set; }
        public int SEQNO { get; set; }
        public int REFCNT { get; set; }
        public int STAMP { get; set; }
    }
}
