//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMRECD
    {
        public string TRNO { get; set; }
        public string TRSIGN { get; set; }
        public string RCPYMODE { get; set; }
        public string ISSBANK { get; set; }
        public string ISSLOC { get; set; }
        public string ISSREFNO { get; set; }
        public Nullable<System.DateTime> ISSDATE { get; set; }
        public string CURRCODE { get; set; }
        public decimal AMT { get; set; }
        public decimal COMAMT { get; set; }
        public decimal NETAMT { get; set; }
        public decimal SNETAMT { get; set; }
        public string REM { get; set; }
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public System.DateTime ENTDATE { get; set; }
        public string MAPCODE { get; set; }
        public string CLCODE { get; set; }
        public string DONE { get; set; }
        public int REFCNT { get; set; }
        public int STAMP { get; set; }
    }
}
