//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQBANK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CQBANK()
        {
            this.CQPARAMs = new HashSet<CQPARAM>();
            this.CQREGs = new HashSet<CQREG>();
        }
    
        public string BANKCODE { get; set; }
        public string BANKACNO { get; set; }
        public string CURRCODE { get; set; }
        public string MAPCODE { get; set; }
        public string TEMCODE { get; set; }
        public int STAMP { get; set; }
    
        public virtual HKBANK HKBANK { get; set; }
        public virtual GLCURR GLCURR { get; set; }
        public virtual HKMAP HKMAP { get; set; }
        public virtual SATEM SATEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CQPARAM> CQPARAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CQREG> CQREGs { get; set; }
    }
}
