//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQITEM
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public string CLCODE { get; set; }
        public short CLADDRID { get; set; }
        public System.DateTime ENTDATE { get; set; }
        public string CURRCODE { get; set; }
        public decimal PAYAMT { get; set; }
        public string PAYDESC { get; set; }
        public string BRANCHCODE { get; set; }
        public string UNITCODE { get; set; }
        public string PRJCODE { get; set; }
        public string STAFFCODE { get; set; }
        public int REFCNT { get; set; }
        public string ITEMST { get; set; }
        public string TRNO { get; set; }
        public Nullable<int> TRID { get; set; }
        public System.DateTime COMPLETED { get; set; }
        public int STAMP { get; set; }
    }
}
