//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCOLASTNO
    {
        public string CONO { get; set; }
        public string LASTCODE { get; set; }
        public string LASTDESC { get; set; }
        public string LASTPFIX { get; set; }
        public int LASTNO { get; set; }
        public int LASTWD { get; set; }
        public string AUTOGEN { get; set; }
        public int STAMP { get; set; }
    }
}
