//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCOAGM
    {
        public string CONO { get; set; }
        public short AGMNO { get; set; }
        public Nullable<System.DateTime> LASTFYE { get; set; }
        public Nullable<System.DateTime> FYETOFILE { get; set; }
        public Nullable<System.DateTime> FILEDFYE { get; set; }
        public Nullable<System.DateTime> AGMLAST { get; set; }
        public Nullable<System.DateTime> AGMEXT { get; set; }
        public Nullable<System.DateTime> REMINDER1 { get; set; }
        public Nullable<System.DateTime> REMINDER2 { get; set; }
        public Nullable<System.DateTime> REMINDER3 { get; set; }
        public Nullable<System.DateTime> AGMDATE { get; set; }
        public Nullable<System.DateTime> AGMFILED { get; set; }
        public string REM { get; set; }
        public int STAMP { get; set; }
        public Nullable<System.DateTime> CIRCDATE { get; set; }
    }
}
