//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCOSHEQD
    {
        public string CONO { get; set; }
        public string PRSCODE { get; set; }
        public string MVTYPE { get; set; }
        public string MVNO { get; set; }
        public int MVID { get; set; }
        public string INMVTYPE { get; set; }
        public string INMVNO { get; set; }
        public int INMVID { get; set; }
        public string OUTMVTYPE { get; set; }
        public string OUTMVNO { get; set; }
        public int OUTMVID { get; set; }
        public System.DateTime MVDATE { get; set; }
        public decimal SHAREAMT { get; set; }
        public int STAMP { get; set; }
    }
}
