//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSJOBM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSJOBM()
        {
            this.CSJOBDs = new HashSet<CSJOBD>();
        }
    
        public string JOBNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public string CONO { get; set; }
        public string REM { get; set; }
        public string JOBSTAFF { get; set; }
        public string JOBPOST { get; set; }
        public int CASECNT { get; set; }
        public int OKCNT { get; set; }
        public string COMPLETE { get; set; }
        public System.DateTime COMPLETED { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSCOMSTR CSCOMSTR { get; set; }
        public virtual HKSTAFF HKSTAFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSJOBD> CSJOBDs { get; set; }
    }
}
