//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSJOBST
    {
        public string JOBNO { get; set; }
        public int CASENO { get; set; }
        public string STAGEFR { get; set; }
        public string STAGETO { get; set; }
        public System.DateTime INDATE { get; set; }
        public string INTIME { get; set; }
        public System.DateTime OUTDATE { get; set; }
        public string SENDMODE { get; set; }
        public string REM { get; set; }
        public string INIDX { get; set; }
        public int STAMP { get; set; }
    }
}
