//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSOFF
    {
        public string TRNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public string CONO { get; set; }
        public string DBTYPE { get; set; }
        public string DBNO { get; set; }
        public int DBID { get; set; }
        public string CRTYPE { get; set; }
        public string CRNO { get; set; }
        public int CRID { get; set; }
        public decimal APPDBITEM1 { get; set; }
        public decimal APPDBITEM2 { get; set; }
        public decimal APPDBITEM { get; set; }
        public decimal APPDBTAX1 { get; set; }
        public decimal APPDBTAX2 { get; set; }
        public decimal APPDBTAX { get; set; }
        public decimal APPDBAMT1 { get; set; }
        public decimal APPDBAMT2 { get; set; }
        public decimal APPDBAMT { get; set; }
        public decimal APPCRITEM1 { get; set; }
        public decimal APPCRITEM2 { get; set; }
        public decimal APPCRITEM { get; set; }
        public decimal APPCRTAX1 { get; set; }
        public decimal APPCRTAX2 { get; set; }
        public decimal APPCRTAX { get; set; }
        public decimal APPCRAMT1 { get; set; }
        public decimal APPCRAMT2 { get; set; }
        public decimal APPCRAMT { get; set; }
        public string REM { get; set; }
        public int SEQNO { get; set; }
        public string POST { get; set; }
        public int STAMP { get; set; }
    }
}
