//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPRSREG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSPRSREG()
        {
            this.CSCOAGTCHGs = new HashSet<CSCOAGTCHG>();
            this.CSCOAGTCHGs1 = new HashSet<CSCOAGTCHG>();
            this.CSCODRCHGs = new HashSet<CSCODRCHG>();
            this.CSCODRCHGs1 = new HashSet<CSCODRCHG>();
            this.CSCOMGRCHGs = new HashSet<CSCOMGRCHG>();
            this.CSCOMGRCHGs1 = new HashSet<CSCOMGRCHG>();
            this.CSCOSECCHGs = new HashSet<CSCOSECCHG>();
            this.CSCOSECCHGs1 = new HashSet<CSCOSECCHG>();
            this.CSCOSECCHGs2 = new HashSet<CSCOSECCHG>();
            this.CSCOSHCHGs = new HashSet<CSCOSHCHG>();
            this.CSCOSHCHGs1 = new HashSet<CSCOSHCHG>();
            this.SFMYNEWDRs = new HashSet<SFMYNEWDR>();
            this.SFMYNEWMGs = new HashSet<SFMYNEWMG>();
            this.SFMYNEWMGs1 = new HashSet<SFMYNEWMG>();
            this.SFMYNEWSCs = new HashSet<SFMYNEWSC>();
            this.SFMYNEWSCs1 = new HashSet<SFMYNEWSC>();
            this.SFMYNEWSCs2 = new HashSet<SFMYNEWSC>();
            this.SFMYNEWSHes = new HashSet<SFMYNEWSH>();
            this.SFMYNEWSHes1 = new HashSet<SFMYNEWSH>();
            this.SFMYSCMVD1 = new HashSet<SFMYSCMVD1>();
            this.SFMYSCMVD11 = new HashSet<SFMYSCMVD1>();
            this.SFMYSCMVD12 = new HashSet<SFMYSCMVD1>();
            this.SFSGDRMVD1 = new HashSet<SFSGDRMVD1>();
            this.SFSGDRMVD11 = new HashSet<SFSGDRMVD1>();
            this.SFSGNEWDRs = new HashSet<SFSGNEWDR>();
            this.SFSGNEWDRs1 = new HashSet<SFSGNEWDR>();
            this.SFSGNEWMGs = new HashSet<SFSGNEWMG>();
            this.SFSGNEWMGs1 = new HashSet<SFSGNEWMG>();
            this.SFSGNEWSCs = new HashSet<SFSGNEWSC>();
            this.SFSGNEWSCs1 = new HashSet<SFSGNEWSC>();
            this.SFSGNEWSCs2 = new HashSet<SFSGNEWSC>();
            this.SFSGNEWSHes = new HashSet<SFSGNEWSH>();
            this.SFSGNEWSHes1 = new HashSet<SFSGNEWSH>();
            this.SFSGSCMVD1 = new HashSet<SFSGSCMVD1>();
            this.SFSGSCMVD11 = new HashSet<SFSGSCMVD1>();
            this.SFSGSCMVD12 = new HashSet<SFSGSCMVD1>();
        }
    
        public string PRSCODE { get; set; }
        public string CTRYCODE { get; set; }
        public string REGTYPE { get; set; }
        public string REGNO { get; set; }
        public string REM { get; set; }
        public int STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOAGTCHG> CSCOAGTCHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOAGTCHG> CSCOAGTCHGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCODRCHG> CSCODRCHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCODRCHG> CSCODRCHGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOMGRCHG> CSCOMGRCHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOMGRCHG> CSCOMGRCHGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOSECCHG> CSCOSECCHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOSECCHG> CSCOSECCHGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOSECCHG> CSCOSECCHGs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOSHCHG> CSCOSHCHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOSHCHG> CSCOSHCHGs1 { get; set; }
        public virtual HKCTRY HKCTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEWDR> SFMYNEWDRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEWMG> SFMYNEWMGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEWMG> SFMYNEWMGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEWSC> SFMYNEWSCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEWSC> SFMYNEWSCs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEWSC> SFMYNEWSCs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEWSH> SFMYNEWSHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEWSH> SFMYNEWSHes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYSCMVD1> SFMYSCMVD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYSCMVD1> SFMYSCMVD11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYSCMVD1> SFMYSCMVD12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGDRMVD1> SFSGDRMVD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGDRMVD1> SFSGDRMVD11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWDR> SFSGNEWDRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWDR> SFSGNEWDRs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWMG> SFSGNEWMGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWMG> SFSGNEWMGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWSC> SFSGNEWSCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWSC> SFSGNEWSCs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWSC> SFSGNEWSCs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWSH> SFSGNEWSHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWSH> SFSGNEWSHes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGSCMVD1> SFSGSCMVD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGSCMVD1> SFSGSCMVD11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGSCMVD1> SFSGSCMVD12 { get; set; }
    }
}
