//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSQT
    {
        public string QTNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public string CONO { get; set; }
        public Nullable<short> COADDRID { get; set; }
        public string ATTN { get; set; }
        public string EMAIL { get; set; }
        public string CONTACTNO { get; set; }
        public string TEMCODE { get; set; }
        public string REM { get; set; }
        public string STAFFCODE { get; set; }
        public string POST { get; set; }
        public string STAGE { get; set; }
        public System.DateTime STAGEDATE { get; set; }
        public string STAGETIME { get; set; }
        public string COMPLETE { get; set; }
        public System.DateTime COMPLETED { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSCOADDR CSCOADDR { get; set; }
        public virtual CSCOMSTR CSCOMSTR { get; set; }
        public virtual SATEM SATEM { get; set; }
        public virtual HKSTAFF HKSTAFF { get; set; }
    }
}
