//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSSTAT
    {
        public string COSTAT { get; set; }
        public string BLANKFILE { get; set; }
        public string FILENOPFIX { get; set; }
        public int FILENOFR { get; set; }
        public int FILENOTO { get; set; }
        public string BLANKSEAL { get; set; }
        public int SEALNOFR { get; set; }
        public int SEALNOTO { get; set; }
        public int STAMP { get; set; }
    }
}
