//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSTAXTYPE
    {
        public string TAXCODE { get; set; }
        public string TAXDESC { get; set; }
        public string TAXTYPE { get; set; }
        public string TAXRCODE { get; set; }
        public decimal TAXRATE { get; set; }
        public System.DateTime EFFECTIVE_START { get; set; }
        public System.DateTime EFFECTIVE_END { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public int STAMP { get; set; }
    }
}
