//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FALDG
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public string ASSETNO { get; set; }
        public string CLSCODE { get; set; }
        public System.DateTime ENTDATE { get; set; }
        public Nullable<System.DateTime> SDATE { get; set; }
        public Nullable<System.DateTime> EDATE { get; set; }
        public Nullable<int> DEPDAYS { get; set; }
        public decimal COST { get; set; }
        public decimal DEP { get; set; }
        public decimal PROV { get; set; }
        public decimal DISP { get; set; }
        public decimal DISPPL { get; set; }
        public decimal WO { get; set; }
        public decimal EXP { get; set; }
        public decimal REC { get; set; }
        public decimal RCP { get; set; }
        public decimal ADV { get; set; }
        public int SEQNO { get; set; }
        public int STAMP { get; set; }
    }
}
