//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMSTR
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public System.DateTime ENTDATE { get; set; }
        public string CLCODE { get; set; }
        public string DONO { get; set; }
        public Nullable<int> DOID { get; set; }
        public string REFNO { get; set; }
        public string ASSETNO { get; set; }
        public string ASSETDESC { get; set; }
        public byte[] ASSETSPEC { get; set; }
        public string SERIALNO { get; set; }
        public decimal COST { get; set; }
        public string REM { get; set; }
        public string POST { get; set; }
        public decimal BOOKVAL { get; set; }
        public System.DateTime LASTTOUCH { get; set; }
        public string COMPLETE { get; set; }
        public System.DateTime COMPLETED { get; set; }
        public string FASSETNO { get; set; }
        public string OUT { get; set; }
        public System.DateTime OUTDATE { get; set; }
        public int SEQNO { get; set; }
        public int REFCNT { get; set; }
        public int STAMP { get; set; }
    
        public virtual APDOD APDOD { get; set; }
        public virtual APDOM APDOM { get; set; }
        public virtual CICL CICL { get; set; }
    }
}
