//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLACC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GLACC()
        {
            this.GLBGMs = new HashSet<GLBGM>();
            this.GLPARAMs = new HashSet<GLPARAM>();
            this.GLRECURDs = new HashSet<GLRECURD>();
            this.GLTRANDs = new HashSet<GLTRAND>();
        }
    
        public string ACCCODE { get; set; }
        public string ACCDESC { get; set; }
        public string ACCCAT { get; set; }
        public string ACCTYPE { get; set; }
        public short ACCLEVEL { get; set; }
        public string MSTRACC { get; set; }
        public int REFCNT { get; set; }
        public int STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLBGM> GLBGMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLPARAM> GLPARAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLRECURD> GLRECURDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLTRAND> GLTRANDs { get; set; }
    }
}
