//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLBGM
    {
        public string ACCCODE { get; set; }
        public string BRANCHCODE { get; set; }
        public string UNITCODE { get; set; }
        public string FINYEAR { get; set; }
        public string CURRCODE { get; set; }
        public int STAMP { get; set; }
    
        public virtual GLACC GLACC { get; set; }
        public virtual GLBRANCH GLBRANCH { get; set; }
        public virtual GLUNIT GLUNIT { get; set; }
        public virtual GLCURR GLCURR { get; set; }
    }
}
