//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLBGD
    {
        public string ACCCODE { get; set; }
        public string BRANCHCODE { get; set; }
        public string UNITCODE { get; set; }
        public string FINYEAR { get; set; }
        public string CURRCODE { get; set; }
        public string FINMONTH { get; set; }
        public decimal DBAMT { get; set; }
        public decimal CRAMT { get; set; }
        public decimal REVDBAMT { get; set; }
        public decimal REVCRAMT { get; set; }
        public int STAMP { get; set; }
    }
}
