//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLYTD
    {
        public string FINYEAR { get; set; }
        public string ACCCODE { get; set; }
        public string BRANCHCODE { get; set; }
        public string UNITCODE { get; set; }
        public string PRJCODE { get; set; }
        public string STAFFCODE { get; set; }
        public string CURRCODE { get; set; }
        public decimal YODEBIT { get; set; }
        public decimal YOCREDIT { get; set; }
        public decimal YCDEBIT { get; set; }
        public decimal YCCREDIT { get; set; }
        public decimal DEBIT01 { get; set; }
        public decimal CREDIT01 { get; set; }
        public decimal DEBIT02 { get; set; }
        public decimal CREDIT02 { get; set; }
        public decimal DEBIT03 { get; set; }
        public decimal CREDIT03 { get; set; }
        public decimal DEBIT04 { get; set; }
        public decimal CREDIT04 { get; set; }
        public decimal DEBIT05 { get; set; }
        public decimal CREDIT05 { get; set; }
        public decimal DEBIT06 { get; set; }
        public decimal CREDIT06 { get; set; }
        public decimal DEBIT07 { get; set; }
        public decimal CREDIT07 { get; set; }
        public decimal DEBIT08 { get; set; }
        public decimal CREDIT08 { get; set; }
        public decimal DEBIT09 { get; set; }
        public decimal CREDIT09 { get; set; }
        public decimal DEBIT10 { get; set; }
        public decimal CREDIT10 { get; set; }
        public decimal DEBIT11 { get; set; }
        public decimal CREDIT11 { get; set; }
        public decimal DEBIT12 { get; set; }
        public decimal CREDIT12 { get; set; }
        public int STAMP { get; set; }
    }
}
