//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HKSTAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HKSTAFF()
        {
            this.CSCOMSTRs = new HashSet<CSCOMSTR>();
            this.CSJOBMs = new HashSet<CSJOBM>();
            this.CSJOBSTFs = new HashSet<CSJOBSTF>();
            this.CSQTs = new HashSet<CSQT>();
            this.HKLOGINMAPs = new HashSet<HKLOGINMAP>();
            this.SFMYADDRCHGs = new HashSet<SFMYADDRCHG>();
            this.SFMYNAMEAPPs = new HashSet<SFMYNAMEAPP>();
            this.SFMYNAMECHGs = new HashSet<SFMYNAMECHG>();
            this.SFMYNEWs = new HashSet<SFMYNEW>();
            this.SFMYSCMVs = new HashSet<SFMYSCMV>();
            this.SFSGADDRCHGs = new HashSet<SFSGADDRCHG>();
            this.SFSGDRMVs = new HashSet<SFSGDRMV>();
            this.SFSGNAMEAPPs = new HashSet<SFSGNAMEAPP>();
            this.SFSGNAMECHGs = new HashSet<SFSGNAMECHG>();
            this.SFSGNEWs = new HashSet<SFSGNEW>();
            this.SFSGSCMVs = new HashSet<SFSGSCMV>();
        }
    
        public string STAFFCODE { get; set; }
        public string STAFFDESC { get; set; }
        public int STAFFLEVEL { get; set; }
        public string MSTRSTAFF { get; set; }
        public int REFCNT { get; set; }
        public int STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOMSTR> CSCOMSTRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSJOBM> CSJOBMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSJOBSTF> CSJOBSTFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSQT> CSQTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HKLOGINMAP> HKLOGINMAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYADDRCHG> SFMYADDRCHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNAMEAPP> SFMYNAMEAPPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNAMECHG> SFMYNAMECHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEW> SFMYNEWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYSCMV> SFMYSCMVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGADDRCHG> SFSGADDRCHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGDRMV> SFSGDRMVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNAMEAPP> SFSGNAMEAPPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNAMECHG> SFSGNAMECHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEW> SFSGNEWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGSCMV> SFSGSCMVs { get; set; }
    }
}
