//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCOFF
    {
        public string TRNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public string CLCODE { get; set; }
        public string DBTYPE { get; set; }
        public string DBNO { get; set; }
        public int DBID { get; set; }
        public string CRTYPE { get; set; }
        public string CRNO { get; set; }
        public int CRID { get; set; }
        public decimal APPAMT { get; set; }
        public string REM { get; set; }
        public string POST { get; set; }
        public int STAMP { get; set; }
    }
}
