//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPARAM
    {
        public string PARAMCODE { get; set; }
        public string PARAMDESC { get; set; }
        public string WRITEAUDIT { get; set; }
        public short EXPDAYS { get; set; }
        public short MAXSESSION { get; set; }
        public short PWMINCHAR { get; set; }
        public short PWRECYCLE { get; set; }
        public short PWFAILLOCK { get; set; }
        public int STAMP { get; set; }
    }
}
