//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPWH
    {
        public string USERID { get; set; }
        public System.DateTime UPDDATE { get; set; }
        public string UPDTIME { get; set; }
        public string PW { get; set; }
    }
}
