//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAUSERDG
    {
        public string USERID { get; set; }
        public string GRPCODE { get; set; }
        public string MODULECODE { get; set; }
        public int STAMP { get; set; }
    
        public virtual SAGRPM SAGRPM { get; set; }
    }
}
