//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFMYSCMVD1
    {
        public string TRNO { get; set; }
        public int TRID { get; set; }
        public string PRSCODE { get; set; }
        public short ADDRID { get; set; }
        public string REGCTRY1 { get; set; }
        public string REGTYPE1 { get; set; }
        public string REGID1 { get; set; }
        public string REGCTRY2 { get; set; }
        public string REGTYPE2 { get; set; }
        public string REGID2 { get; set; }
        public string REGCTRY3 { get; set; }
        public string REGTYPE3 { get; set; }
        public string REGID3 { get; set; }
        public string REM { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSPR CSPR { get; set; }
        public virtual CSPRSADDR CSPRSADDR { get; set; }
        public virtual CSPRSREG CSPRSREG { get; set; }
        public virtual CSPRSREG CSPRSREG1 { get; set; }
        public virtual CSPRSREG CSPRSREG2 { get; set; }
    }
}
