//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSGNEWDRD3
    {
        public string TRNO { get; set; }
        public string PRSCODE { get; set; }
        public string ENTTYPE { get; set; }
        public string DIPRSCODE { get; set; }
        public System.DateTime DIADATE { get; set; }
        public string DIEQCODE { get; set; }
        public decimal DISHAREAMT { get; set; }
        public string DIEQCONSIDER { get; set; }
        public decimal DIAMT { get; set; }
        public string RELCODE { get; set; }
        public string REM { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSEQ CSEQ { get; set; }
        public virtual CSPR CSPR { get; set; }
        public virtual HKREL HKREL { get; set; }
    }
}
