//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIBF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIBF()
        {
            this.SIRKBFs = new HashSet<SIRKBF>();
            this.SISTFSTBFs = new HashSet<SISTFSTBF>();
            this.SSBFTRMs = new HashSet<SSBFTRM>();
        }
    
        public string BFCODE { get; set; }
        public string BFDESC { get; set; }
        public string BFCOND { get; set; }
        public int BFYRRECUR { get; set; }
        public string BFYRBASE { get; set; }
        public string BFPROB { get; set; }
        public string BFMAPSFIX { get; set; }
        public int STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIRKBF> SIRKBFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTFSTBF> SISTFSTBFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSBFTRM> SSBFTRMs { get; set; }
    }
}
