//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SILNMETHOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SILNMETHOD()
        {
            this.SSLNTRMs = new HashSet<SSLNTRM>();
        }
    
        public string METHODCODE { get; set; }
        public string METHODDESC { get; set; }
        public string METHODTYPE { get; set; }
        public string PITYPE { get; set; }
        public string PICOMP { get; set; }
        public string DCFLAG { get; set; }
        public string DCCOMP { get; set; }
        public string DIFLAG { get; set; }
        public string DICOMP { get; set; }
        public int STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSLNTRM> SSLNTRMs { get; set; }
    }
}
