//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SILN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SILN()
        {
            this.SILNMSTRs = new HashSet<SILNMSTR>();
            this.SIRKLNs = new HashSet<SIRKLN>();
            this.SISTFSTLNs = new HashSet<SISTFSTLN>();
            this.SSLNTRMs = new HashSet<SSLNTRM>();
        }
    
        public string LNCODE { get; set; }
        public string LNDESC { get; set; }
        public string LNPROB { get; set; }
        public string LNMAPSFIX { get; set; }
        public byte[] LNNAR { get; set; }
        public int STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SILNMSTR> SILNMSTRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIRKLN> SIRKLNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTFSTLN> SISTFSTLNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSLNTRM> SSLNTRMs { get; set; }
    }
}
