//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SILNLDG
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public System.DateTime ENTDATE { get; set; }
        public string INVTYPE { get; set; }
        public string INVNO { get; set; }
        public Nullable<int> INVID { get; set; }
        public string LOANNO { get; set; }
        public string STAFFCODE { get; set; }
        public Nullable<System.DateTime> ACCRSDATE { get; set; }
        public Nullable<System.DateTime> ACCREDATE { get; set; }
        public int ACCRDAYS { get; set; }
        public decimal PC { get; set; }
        public decimal PCREC { get; set; }
        public decimal PCWOPL { get; set; }
        public decimal PCWOBS { get; set; }
        public decimal PI { get; set; }
        public decimal PIREC { get; set; }
        public decimal PIINC { get; set; }
        public decimal PISUSPL { get; set; }
        public decimal PISUSBS { get; set; }
        public decimal PIREV { get; set; }
        public decimal PIWOPL { get; set; }
        public decimal PIWOBS { get; set; }
        public decimal DC { get; set; }
        public decimal DCREC { get; set; }
        public decimal DCINC { get; set; }
        public decimal DCSUSPL { get; set; }
        public decimal DCSUSBS { get; set; }
        public decimal DCREV { get; set; }
        public decimal DCWOPL { get; set; }
        public decimal DCWOBS { get; set; }
        public decimal DI { get; set; }
        public decimal DIREC { get; set; }
        public decimal DIINC { get; set; }
        public decimal DISUSPL { get; set; }
        public decimal DISUSBS { get; set; }
        public decimal DIREV { get; set; }
        public decimal DIWOPL { get; set; }
        public decimal DIWOBS { get; set; }
        public decimal FE { get; set; }
        public decimal FEREC { get; set; }
        public decimal FEWOPL { get; set; }
        public decimal FEWOBS { get; set; }
        public decimal RCP { get; set; }
        public int SEQNO { get; set; }
        public int STAMP { get; set; }
    }
}
