//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SILNST
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public string LOANNO { get; set; }
        public string STAFFCODE { get; set; }
        public System.DateTime SDATE { get; set; }
        public System.DateTime EDATE { get; set; }
        public string METHODCODE { get; set; }
        public string RATECODE { get; set; }
        public decimal SPRATE { get; set; }
        public decimal PRATE { get; set; }
        public string CHRGDC { get; set; }
        public string CHRGDI { get; set; }
        public string NPL { get; set; }
        public string RCMODE { get; set; }
        public string REM { get; set; }
        public string POST { get; set; }
        public int STAMP { get; set; }
    }
}
