//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SILNINVWK
    {
        public string INVTYPE { get; set; }
        public string INVNO { get; set; }
        public int INVID { get; set; }
        public string LOANNO { get; set; }
        public string STAFFCODE { get; set; }
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public System.DateTime SDATE { get; set; }
        public System.DateTime EDATE { get; set; }
        public decimal BASEAMT { get; set; }
        public string METHODCODE { get; set; }
        public string RATECODE { get; set; }
        public decimal RATE { get; set; }
        public decimal SPRATE { get; set; }
        public decimal PRATE { get; set; }
        public decimal INVAMT { get; set; }
        public int STAMP { get; set; }
    }
}
