//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SILNDD
    {
        public string TRNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public string LOANNO { get; set; }
        public string STAFFCODE { get; set; }
        public string CLCODE { get; set; }
        public short CLADDRID { get; set; }
        public decimal DDAMT { get; set; }
        public string PYMODE { get; set; }
        public string PYMAPCODE { get; set; }
        public string REM { get; set; }
        public int SEQNO { get; set; }
        public string POST { get; set; }
        public string CFLAG { get; set; }
        public string CTRNO { get; set; }
        public Nullable<System.DateTime> CVDATE { get; set; }
        public string CREM { get; set; }
        public Nullable<int> CSEQNO { get; set; }
        public string CPOST { get; set; }
        public int STAMP { get; set; }
    
        public virtual CICL CICL { get; set; }
        public virtual CICLADDR CICLADDR { get; set; }
        public virtual SILNMSTR SILNMSTR { get; set; }
    }
}
