//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SILV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SILV()
        {
            this.SIRKLVs = new HashSet<SIRKLV>();
            this.SISTFSTLVs = new HashSet<SISTFSTLV>();
            this.SISTFSTLVADJs = new HashSet<SISTFSTLVADJ>();
            this.SSLVTRDLs = new HashSet<SSLVTRDL>();
        }
    
        public string LVCODE { get; set; }
        public string LVDESC { get; set; }
        public string LVCOND { get; set; }
        public string LVAPPCOND { get; set; }
        public string LVINCHOL { get; set; }
        public string LVCANCF { get; set; }
        public string LVPROB { get; set; }
        public string LVEARNCOND { get; set; }
        public string LVHALFDAY { get; set; }
        public string LVSHOWBAL { get; set; }
        public int STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIRKLV> SIRKLVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTFSTLV> SISTFSTLVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTFSTLVADJ> SISTFSTLVADJs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSLVTRDL> SSLVTRDLs { get; set; }
    }
}
