//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTFSTLN
    {
        public string STAFFCODE { get; set; }
        public string FINYEAR { get; set; }
        public string LNCODE { get; set; }
        public decimal LNLMT { get; set; }
        public decimal LNUTIL { get; set; }
        public decimal LNPEND { get; set; }
        public string FINCLOSE { get; set; }
        public int ROWNO { get; set; }
        public int STAMP { get; set; }
    
        public virtual SILN SILN { get; set; }
    }
}
