//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTFST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SISTFST()
        {
            this.SILNMSTRs = new HashSet<SILNMSTR>();
            this.SISTFSTLVADJs = new HashSet<SISTFSTLVADJ>();
            this.SISTFSTMVs = new HashSet<SISTFSTMV>();
            this.SSBFTRMs = new HashSet<SSBFTRM>();
            this.SSLNTRMs = new HashSet<SSLNTRM>();
            this.SSLVTRDS = new HashSet<SSLVTRD>();
            this.SSLVTRMs = new HashSet<SSLVTRM>();
            this.SSLVTRMs1 = new HashSet<SSLVTRM>();
            this.SSLVTRMs2 = new HashSet<SSLVTRM>();
            this.SSSPPDs = new HashSet<SSSPPD>();
            this.SSSPPMs = new HashSet<SSSPPM>();
            this.SSSPPMs1 = new HashSet<SSSPPM>();
            this.SSSPPMs2 = new HashSet<SSSPPM>();
        }
    
        public string STAFFCODE { get; set; }
        public string STAFFNO { get; set; }
        public System.DateTime JDATE { get; set; }
        public string JST { get; set; }
        public Nullable<System.DateTime> JDUEDATE { get; set; }
        public string JREM { get; set; }
        public string JPOST { get; set; }
        public int JSEQNO { get; set; }
        public string CFLAG { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CREM { get; set; }
        public string CPOST { get; set; }
        public Nullable<int> CSEQNO { get; set; }
        public string RFLAG { get; set; }
        public Nullable<System.DateTime> RDATE { get; set; }
        public Nullable<System.DateTime> RLASTDATE { get; set; }
        public string RREM { get; set; }
        public string RPOST { get; set; }
        public Nullable<int> RSEQNO { get; set; }
        public System.DateTime LASTTOUCH { get; set; }
        public int STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SILNMSTR> SILNMSTRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTFSTLVADJ> SISTFSTLVADJs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTFSTMV> SISTFSTMVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSBFTRM> SSBFTRMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSLNTRM> SSLNTRMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSLVTRD> SSLVTRDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSLVTRM> SSLVTRMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSLVTRM> SSLVTRMs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSLVTRM> SSLVTRMs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSSPPD> SSSPPDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSSPPM> SSSPPMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSSPPM> SSSPPMs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSSPPM> SSSPPMs2 { get; set; }
    }
}
