//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTFSTBFMV
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public string STAFFCODE { get; set; }
        public string FINYEAR { get; set; }
        public string BFCODE { get; set; }
        public System.DateTime MVDATE { get; set; }
        public decimal BFLMT { get; set; }
        public decimal BFUTIL { get; set; }
        public decimal BFPEND { get; set; }
        public int SEQNO { get; set; }
        public int STAMP { get; set; }
    }
}
