//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRSGPPD
    {
        public string TRNO { get; set; }
        public int TRID { get; set; }
        public string TRTYPE { get; set; }
        public string SECAC { get; set; }
        public string BANKCODE { get; set; }
        public string DACODE { get; set; }
        public string SCHEME { get; set; }
        public string NATIONALITY { get; set; }
        public string SGPR { get; set; }
        public string NRIC { get; set; }
        public string HOLDERNAME { get; set; }
        public decimal QTYAPP { get; set; }
        public decimal QTYALLOT { get; set; }
        public string REGREF { get; set; }
        public string ADDRESS { get; set; }
        public string POSTAL { get; set; }
        public string ERRORCODE { get; set; }
        public string REM { get; set; }
        public decimal CHECKSUM { get; set; }
        public int STAMP { get; set; }
    
        public virtual SRSGBANK SRSGBANK { get; set; }
        public virtual SRSGDA SRSGDA { get; set; }
    }
}
