//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSLNTRM
    {
        public string TRNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public string LOGINID { get; set; }
        public string STAFFCODE { get; set; }
        public string LNCODE { get; set; }
        public byte[] LNNAR { get; set; }
        public decimal LNAMT { get; set; }
        public string METHODCODE { get; set; }
        public string RATECODE { get; set; }
        public decimal SPRATE { get; set; }
        public decimal PRATE { get; set; }
        public string REM { get; set; }
        public string FINYEAR { get; set; }
        public string POST { get; set; }
        public int SEQNO { get; set; }
        public string OC { get; set; }
        public Nullable<System.DateTime> OCDATE { get; set; }
        public string OCREM { get; set; }
        public string OCPOST { get; set; }
        public int STAMP { get; set; }
    
        public virtual SILN SILN { get; set; }
        public virtual SILNMETHOD SILNMETHOD { get; set; }
        public virtual SIRATEM SIRATEM { get; set; }
        public virtual SISTFST SISTFST { get; set; }
    }
}
