//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSLVTRM
    {
        public string TRNO { get; set; }
        public string TRTYPE { get; set; }
        public string TRLOGINID { get; set; }
        public string LOGINID { get; set; }
        public System.DateTime VDATE { get; set; }
        public string STAFFCODE { get; set; }
        public string REM { get; set; }
        public System.DateTime MINLVDATE { get; set; }
        public int SEQNO { get; set; }
        public string TRDONE { get; set; }
        public string RFLAG { get; set; }
        public string RRESULT { get; set; }
        public Nullable<System.DateTime> RDATE { get; set; }
        public string RSTAFFCODE { get; set; }
        public string RLOGINID { get; set; }
        public string RREM { get; set; }
        public Nullable<int> RSEQNO { get; set; }
        public string AFLAG { get; set; }
        public string ARESULT { get; set; }
        public Nullable<System.DateTime> ADATE { get; set; }
        public string ASTAFFCODE { get; set; }
        public string ALOGINID { get; set; }
        public string AREM { get; set; }
        public Nullable<int> ASEQNO { get; set; }
        public string CFLAG { get; set; }
        public string CBY { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<int> CSEQNO { get; set; }
        public int STAMP { get; set; }
    
        public virtual SISTFST SISTFST { get; set; }
        public virtual SISTFST SISTFST1 { get; set; }
        public virtual SISTFST SISTFST2 { get; set; }
    }
}
