//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTEMAILGD
    {
        public string MAILGCODE { get; set; }
        public string CONO { get; set; }
        public string PRSCODE { get; set; }
        public int STAMP { get; set; }
    }
}
