//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class APDOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APDOD()
        {
            this.FAMSTRs = new HashSet<FAMSTR>();
        }
    
        public string TRNO { get; set; }
        public int TRID { get; set; }
        public System.DateTime VDATE { get; set; }
        public string CLCODE { get; set; }
        public string DONO { get; set; }
        public System.DateTime DODATE { get; set; }
        public string PONO { get; set; }
        public Nullable<int> POID { get; set; }
        public decimal RQTY { get; set; }
        public int STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAMSTR> FAMSTRs { get; set; }
    }
}
