//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class APINVD
    {
        public string TRNO { get; set; }
        public int TRID { get; set; }
        public System.DateTime VDATE { get; set; }
        public string CLCODE { get; set; }
        public string INVNO { get; set; }
        public System.DateTime INVDATE { get; set; }
        public string DONO { get; set; }
        public string PONO { get; set; }
        public Nullable<int> POID { get; set; }
        public string ITEMDESC { get; set; }
        public string DBMAPCODE { get; set; }
        public string BRANCHCODE { get; set; }
        public string UNITCODE { get; set; }
        public string PRJCODE { get; set; }
        public string STAFFCODE { get; set; }
        public string CURRCODE { get; set; }
        public decimal ITEMAMT { get; set; }
        public int STAMP { get; set; }
    }
}
