//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOM
    {
        public string TRNO { get; set; }
        public string TRTYPE { get; set; }
        public System.DateTime VDATE { get; set; }
        public System.DateTime EXPIRY { get; set; }
        public string CLCODE { get; set; }
        public Nullable<short> CLADDRID { get; set; }
        public string ATTN { get; set; }
        public string REM { get; set; }
        public string POST { get; set; }
        public string CFLAG { get; set; }
        public string CTRNO { get; set; }
        public Nullable<System.DateTime> CVDATE { get; set; }
        public string CREM { get; set; }
        public string CPOST { get; set; }
        public string RTRNO { get; set; }
        public string CURRCODE { get; set; }
        public decimal POAMT { get; set; }
        public decimal POQTY { get; set; }
        public decimal POQTYOS { get; set; }
        public string COMPLETE { get; set; }
        public System.DateTime COMPLETED { get; set; }
        public int REFCNT { get; set; }
        public int STAMP { get; set; }
    
        public virtual CICL CICL { get; set; }
        public virtual CICLADDR CICLADDR { get; set; }
        public virtual GLCURR GLCURR { get; set; }
    }
}
