//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOD
    {
        public string TRNO { get; set; }
        public int TRID { get; set; }
        public string ITEMDESC { get; set; }
        public byte[] ITEMSPEC { get; set; }
        public decimal QTY { get; set; }
        public string QTYTYPE { get; set; }
        public string CURRCODE { get; set; }
        public decimal QTYPRICE { get; set; }
        public decimal PRICE { get; set; }
        public string REM { get; set; }
        public decimal QTYOS { get; set; }
        public string COMPLETE { get; set; }
        public System.DateTime COMPLETED { get; set; }
        public int STAMP { get; set; }
    }
}
