//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASPNETUSER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASPNETUSER()
        {
            this.ASPNETUSERCLAIMS = new HashSet<ASPNETUSERCLAIM>();
            this.ASPNETUSERLOGINS = new HashSet<ASPNETUSERLOGIN>();
            this.ASPNETROLES = new HashSet<ASPNETROLE>();
        }
    
        public string ID { get; set; }
        public string EMAIL { get; set; }
        public string EMAILCONFIRMED { get; set; }
        public string PASSWORDHASH { get; set; }
        public string SECURITYSTAMP { get; set; }
        public string PHONENUMBER { get; set; }
        public string PHONENUMBERCONFIRMED { get; set; }
        public string TWOFACTORENABLED { get; set; }
        public Nullable<System.DateTime> LOCKOUTENDDATEUTC { get; set; }
        public string LOCKOUTENABLED { get; set; }
        public int ACCESSFAILEDCOUNT { get; set; }
        public string USERNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASPNETUSERCLAIM> ASPNETUSERCLAIMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASPNETUSERLOGIN> ASPNETUSERLOGINS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASPNETROLE> ASPNETROLES { get; set; }
    }
}
