//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CICLPIC
    {
        public string CLCODE { get; set; }
        public string CONTACT { get; set; }
        public string TITLE { get; set; }
        public string DESIG { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string MOBILE1 { get; set; }
        public string MOBILE2 { get; set; }
        public string FAX1 { get; set; }
        public string FAX2 { get; set; }
        public string EMAIL { get; set; }
        public string REM { get; set; }
        public int STAMP { get; set; }
    
        public virtual HKTITLE HKTITLE { get; set; }
    }
}
