//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CICL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CICL()
        {
            this.APCNMs = new HashSet<APCNM>();
            this.APDOMs = new HashSet<APDOM>();
            this.APINVMs = new HashSet<APINVM>();
            this.APPOMs = new HashSet<APPOM>();
            this.CSCOSECs = new HashSet<CSCOSEC>();
            this.CSPYMs = new HashSet<CSPYM>();
            this.FAMSTRs = new HashSet<FAMSTR>();
            this.FAOUTs = new HashSet<FAOUT>();
            this.PCTRANMs = new HashSet<PCTRANM>();
            this.SILNDDs = new HashSet<SILNDD>();
        }
    
        public string CLCODE { get; set; }
        public string CONSTCODE { get; set; }
        public string CLNAME { get; set; }
        public string CLTITLE { get; set; }
        public string GENDER { get; set; }
        public string NATION { get; set; }
        public string RACE { get; set; }
        public string BILLNAME { get; set; }
        public string REM { get; set; }
        public string REFCODE { get; set; }
        public string SYSGEN { get; set; }
        public int STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APCNM> APCNMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APDOM> APDOMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APINVM> APINVMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOM> APPOMs { get; set; }
        public virtual HKCONST HKCONST { get; set; }
        public virtual HKNATION HKNATION { get; set; }
        public virtual HKRACE HKRACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOSEC> CSCOSECs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSPYM> CSPYMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAMSTR> FAMSTRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAOUT> FAOUTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCTRANM> PCTRANMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SILNDD> SILNDDs { get; set; }
    }
}
