//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMRECM
    {
        public string TRNO { get; set; }
        public string TRTYPE { get; set; }
        public string TRSIGN { get; set; }
        public string RCPYMODE { get; set; }
        public string MAPCODE { get; set; }
        public System.DateTime ENTDATE { get; set; }
        public string ISSBANK { get; set; }
        public string ISSLOC { get; set; }
        public string ISSREFNO { get; set; }
        public Nullable<System.DateTime> ISSDATE { get; set; }
        public string CURRCODE { get; set; }
        public decimal DBAMT { get; set; }
        public decimal CRAMT { get; set; }
        public string REM { get; set; }
        public string POST { get; set; }
        public string TRMARK { get; set; }
        public System.DateTime TRMARKD { get; set; }
        public string BSNO { get; set; }
        public Nullable<int> BSID { get; set; }
        public int STAMP { get; set; }
    }
}
