//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQPAPER
    {
        public string BANKCODE { get; set; }
        public string BANKACNO { get; set; }
        public string CHQNO { get; set; }
        public string RTRNO { get; set; }
        public System.DateTime RDATE { get; set; }
        public string ITRNO { get; set; }
        public Nullable<int> ITRID { get; set; }
        public System.DateTime IDATE { get; set; }
        public string CSOURCE { get; set; }
        public string CTRNO { get; set; }
        public System.DateTime CDATE { get; set; }
        public string CREM { get; set; }
        public string CPOST { get; set; }
        public string CHQST { get; set; }
        public int STAMP { get; set; }
    }
}
