//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCANC3P
    {
        public string TRNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public decimal CANCAMT { get; set; }
        public string CONO { get; set; }
        public string APPTYPE { get; set; }
        public string APPNO { get; set; }
        public Nullable<int> APPID { get; set; }
        public string REM { get; set; }
        public int SEQNO { get; set; }
        public string POST { get; set; }
        public int STAMP { get; set; }
    }
}
