//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCOPARENT
    {
        public string CONO { get; set; }
        public string CONOPARENT { get; set; }
        public System.DateTime ADATE { get; set; }
        public Nullable<System.DateTime> RDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public string REM { get; set; }
        public int ROWNO { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSCOMSTR CSCOMSTR { get; set; }
    }
}
