//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCOSHEQ
    {
        public string CONO { get; set; }
        public string PRSCODE { get; set; }
        public string MVNO { get; set; }
        public int MVID { get; set; }
        public string MVTYPE { get; set; }
        public System.DateTime MVDATE { get; set; }
        public string MVSIGN { get; set; }
        public Nullable<int> FOLIONOSRC { get; set; }
        public string EQCODE { get; set; }
        public string SCRIPT { get; set; }
        public string CERTNO { get; set; }
        public decimal SHAREAMT { get; set; }
        public decimal SSHAREAMT { get; set; }
        public decimal SHAREOS { get; set; }
        public decimal AMT { get; set; }
        public decimal SAMT { get; set; }
        public string REM { get; set; }
        public int REFCNT { get; set; }
        public string COMPLETE { get; set; }
        public System.DateTime COMPLETED { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSCOSH CSCOSH { get; set; }
        public virtual CSEQ CSEQ { get; set; }
    }
}
