//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCOSTAT
    {
        public string CONO { get; set; }
        public System.DateTime SDATE { get; set; }
        public string COSTAT { get; set; }
        public string FILETYPE { get; set; }
        public string FILELOC { get; set; }
        public string SEALLOC { get; set; }
        public System.DateTime EDATE { get; set; }
        public int ROWNO { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSCOMSTR CSCOMSTR { get; set; }
    }
}
