//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCODR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSCODR()
        {
            this.SFMYADDRCHGs = new HashSet<SFMYADDRCHG>();
            this.SFMYNAMECHGs = new HashSet<SFMYNAMECHG>();
            this.SFMYSCMVs = new HashSet<SFMYSCMV>();
            this.SFSGADDRCHGs = new HashSet<SFSGADDRCHG>();
            this.SFSGDRMVD2 = new HashSet<SFSGDRMVD2>();
            this.SFSGNAMECHGs = new HashSet<SFSGNAMECHG>();
            this.SFSGSCMVs = new HashSet<SFSGSCMV>();
            this.CSCODRCHGs = new HashSet<CSCODRCHG>();
        }
    
        public string CONO { get; set; }
        public string PRSCODE { get; set; }
        public System.DateTime ADATE { get; set; }
        public Nullable<System.DateTime> RDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public string REM { get; set; }
        public int ROWNO { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSPR CSPR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYADDRCHG> SFMYADDRCHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNAMECHG> SFMYNAMECHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYSCMV> SFMYSCMVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGADDRCHG> SFSGADDRCHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGDRMVD2> SFSGDRMVD2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNAMECHG> SFSGNAMECHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGSCMV> SFSGSCMVs { get; set; }
        public virtual CSCOMSTR CSCOMSTR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCODRCHG> CSCODRCHGs { get; set; }
    }
}
