//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCOSH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSCOSH()
        {
            this.CSCOSHCHGs = new HashSet<CSCOSHCHG>();
            this.CSCOSHEQs = new HashSet<CSCOSHEQ>();
            this.CSCOSHEQDs = new HashSet<CSCOSHEQD>();
        }
    
        public string CONO { get; set; }
        public string PRSCODE { get; set; }
        public System.DateTime EFFDATE { get; set; }
        public Nullable<System.DateTime> TERDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public int FOLIONO { get; set; }
        public string REM { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSPR CSPR { get; set; }
        public virtual CSCOMSTR CSCOMSTR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOSHCHG> CSCOSHCHGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOSHEQ> CSCOSHEQs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOSHEQD> CSCOSHEQDs { get; set; }
    }
}
