//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCOMSTR
    {
        public string CONO { get; set; }
        public System.DateTime INCDATE { get; set; }
        public string INCCTRY { get; set; }
        public string CONSTCODE { get; set; }
        public string INTYPE { get; set; }
        public byte[] PRINOBJ { get; set; }
        public string CONAME { get; set; }
        public string PINDCODE { get; set; }
        public string SINDCODE { get; set; }
        public string WEB { get; set; }
        public string COSTAT { get; set; }
        public System.DateTime COSTATD { get; set; }
        public string FILETYPE { get; set; }
        public string FILELOC { get; set; }
        public string SEALLOC { get; set; }
        public string STAFFCODE { get; set; }
        public string SPECIALRE { get; set; }
        public byte[] CMMT { get; set; }
        public string REM { get; set; }
        public string SXCODE { get; set; }
        public string SXNAME { get; set; }
        public string REFCODE { get; set; }
        public int SEQNO { get; set; }
        public int STAMP { get; set; }
        public string COREGNO { get; set; }
        public string ARRE { get; set; }
    
        public virtual HKCTRY HKCTRY { get; set; }
        public virtual HKCONST HKCONST { get; set; }
        public virtual HKSTAFF HKSTAFF { get; set; }
    }
}
