//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSDNM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSDNM()
        {
            this.CSDNDs = new HashSet<CSDND>();
        }
    
        public string TRNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public string CONO { get; set; }
        public Nullable<short> COADDRID { get; set; }
        public string ATTN { get; set; }
        public string REM { get; set; }
        public int SEQNO { get; set; }
        public string POST { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSCOMSTR CSCOMSTR { get; set; }
        public virtual CSCOADDR CSCOADDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSDND> CSDNDs { get; set; }
    }
}
