//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSLDG
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public string CONO { get; set; }
        public string JOBNO { get; set; }
        public Nullable<int> CASENO { get; set; }
        public string CASECODE { get; set; }
        public System.DateTime ENTDATE { get; set; }
        public decimal DEP { get; set; }
        public decimal DEPREC { get; set; }
        public decimal FEE1 { get; set; }
        public decimal FEE2 { get; set; }
        public decimal FEEREC1 { get; set; }
        public decimal FEEREC2 { get; set; }
        public decimal TAX1 { get; set; }
        public decimal TAX2 { get; set; }
        public decimal TAXREC1 { get; set; }
        public decimal TAXREC2 { get; set; }
        public decimal WORK1 { get; set; }
        public decimal WORK2 { get; set; }
        public decimal WORKREC1 { get; set; }
        public decimal WORKREC2 { get; set; }
        public decimal DISB1 { get; set; }
        public decimal DISB2 { get; set; }
        public decimal DISBREC1 { get; set; }
        public decimal DISBREC2 { get; set; }
        public decimal RECEIPT { get; set; }
        public decimal ADVANCE { get; set; }
        public int SEQNO { get; set; }
        public int STAMP { get; set; }
        public Nullable<decimal> REIMB1 { get; set; }
        public Nullable<decimal> REIMB2 { get; set; }
        public Nullable<decimal> REIMBREC1 { get; set; }
        public Nullable<decimal> REIMBREC2 { get; set; }
    }
}
