//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPRF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSPRF()
        {
            this.CSBILLs = new HashSet<CSBILL>();
        }
    
        public string PRFNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public int DUEDAYS { get; set; }
        public System.DateTime DUEDATE { get; set; }
        public string CONO { get; set; }
        public Nullable<short> COADDRID { get; set; }
        public string ATTN { get; set; }
        public string REM { get; set; }
        public int SEQNO { get; set; }
        public string INVALLOC { get; set; }
        public string INVNO { get; set; }
        public Nullable<int> INVID { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSCOADDR CSCOADDR { get; set; }
        public virtual CSCOMSTR CSCOMSTR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSBILL> CSBILLs { get; set; }
    }
}
