//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSPR()
        {
            this.CSCOADTs = new HashSet<CSCOADT>();
            this.CSCOAGTs = new HashSet<CSCOAGT>();
            this.CSCOCMs = new HashSet<CSCOCM>();
            this.CSCODEBs = new HashSet<CSCODEB>();
            this.CSCODRs = new HashSet<CSCODR>();
            this.CSCOMGRs = new HashSet<CSCOMGR>();
            this.CSCOPICs = new HashSet<CSCOPIC>();
            this.CSCOSECs = new HashSet<CSCOSEC>();
            this.CSCOSHes = new HashSet<CSCOSH>();
            this.CSGRPPICs = new HashSet<CSGRPPIC>();
            this.SFMYNEWDRs = new HashSet<SFMYNEWDR>();
            this.SFMYNEWMGs = new HashSet<SFMYNEWMG>();
            this.SFMYNEWSCs = new HashSet<SFMYNEWSC>();
            this.SFMYNEWSHes = new HashSet<SFMYNEWSH>();
            this.SFMYSCMVD1 = new HashSet<SFMYSCMVD1>();
            this.SFSGDRMVD1 = new HashSet<SFSGDRMVD1>();
            this.SFSGNEWBKD1 = new HashSet<SFSGNEWBKD1>();
            this.SFSGNEWDRD1 = new HashSet<SFSGNEWDRD1>();
            this.SFSGNEWDRD2 = new HashSet<SFSGNEWDRD2>();
            this.SFSGNEWDRD3 = new HashSet<SFSGNEWDRD3>();
            this.SFSGNEWDRs = new HashSet<SFSGNEWDR>();
            this.SFSGNEWMGs = new HashSet<SFSGNEWMG>();
            this.SFSGNEWSCs = new HashSet<SFSGNEWSC>();
            this.SFSGNEWSHes = new HashSet<SFSGNEWSH>();
            this.SFSGSCMVD1 = new HashSet<SFSGSCMVD1>();
        }
    
        public string PRSCODE { get; set; }
        public string CONSTCODE { get; set; }
        public string PRSNAME { get; set; }
        public string PRSTITLE { get; set; }
        public string NATION { get; set; }
        public string RACE { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CTRYINC { get; set; }
        public string MOBILE1 { get; set; }
        public string MOBILE2 { get; set; }
        public string EMAIL { get; set; }
        public string OCCUPATION { get; set; }
        public string REM { get; set; }
        public int STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOADT> CSCOADTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOAGT> CSCOAGTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOCM> CSCOCMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCODEB> CSCODEBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCODR> CSCODRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOMGR> CSCOMGRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOPIC> CSCOPICs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOSEC> CSCOSECs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSCOSH> CSCOSHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSGRPPIC> CSGRPPICs { get; set; }
        public virtual HKCONST HKCONST { get; set; }
        public virtual HKTITLE HKTITLE { get; set; }
        public virtual HKNATION HKNATION { get; set; }
        public virtual HKRACE HKRACE { get; set; }
        public virtual HKCTRY HKCTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEWDR> SFMYNEWDRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEWMG> SFMYNEWMGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEWSC> SFMYNEWSCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYNEWSH> SFMYNEWSHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFMYSCMVD1> SFMYSCMVD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGDRMVD1> SFSGDRMVD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWBKD1> SFSGNEWBKD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWDRD1> SFSGNEWDRD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWDRD2> SFSGNEWDRD2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWDRD3> SFSGNEWDRD3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWDR> SFSGNEWDRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWMG> SFSGNEWMGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWSC> SFSGNEWSCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGNEWSH> SFSGNEWSHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFSGSCMVD1> SFSGSCMVD1 { get; set; }
    }
}
