//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSTRAND
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public string DBTYPE { get; set; }
        public string DBNO { get; set; }
        public int DBID { get; set; }
        public string CRTYPE { get; set; }
        public string CRNO { get; set; }
        public int CRID { get; set; }
        public System.DateTime APPDATE { get; set; }
        public decimal APPITEM1 { get; set; }
        public decimal APPITEM2 { get; set; }
        public decimal APPITEM { get; set; }
        public decimal APPTAX1 { get; set; }
        public decimal APPTAX2 { get; set; }
        public decimal APPTAX { get; set; }
        public decimal APPAMT1 { get; set; }
        public decimal APPAMT2 { get; set; }
        public decimal APPAMT { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSTRANM CSTRANM { get; set; }
    }
}
