//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSTRANM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSTRANM()
        {
            this.CSOFF = new HashSet<CSOFF>();
            this.CSOFFs = new HashSet<CSOFF>();
        }
    
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public string CONO { get; set; }
        public string JOBNO { get; set; }
        public Nullable<int> CASENO { get; set; }
        public string CASECODE { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public System.DateTime ENTDATE { get; set; }
        public string TRTYPE { get; set; }
        public string TRDESC { get; set; }
        public decimal TRITEM1 { get; set; }
        public decimal TRITEM2 { get; set; }
        public decimal TRITEM { get; set; }
        public decimal TRTAX1 { get; set; }
        public decimal TRTAX2 { get; set; }
        public decimal TRTAX { get; set; }
        public decimal TRAMT1 { get; set; }
        public decimal TRAMT2 { get; set; }
        public decimal TRAMT { get; set; }
        public string TRSIGN { get; set; }
        public decimal TRSITEM1 { get; set; }
        public decimal TRSITEM2 { get; set; }
        public decimal TRSITEM { get; set; }
        public decimal TRSTAX1 { get; set; }
        public decimal TRSTAX2 { get; set; }
        public decimal TRSTAX { get; set; }
        public decimal TRSAMT1 { get; set; }
        public decimal TRSAMT2 { get; set; }
        public decimal TRSAMT { get; set; }
        public decimal TRITEMOS1 { get; set; }
        public decimal TRITEMOS2 { get; set; }
        public decimal TRITEMOS { get; set; }
        public decimal TRTAXOS1 { get; set; }
        public decimal TRTAXOS2 { get; set; }
        public decimal TRTAXOS { get; set; }
        public decimal TROS1 { get; set; }
        public decimal TROS2 { get; set; }
        public decimal TROS { get; set; }
        public string APPTYPE { get; set; }
        public string APPNO { get; set; }
        public Nullable<int> APPID { get; set; }
        public decimal APPITEM1 { get; set; }
        public decimal APPITEM2 { get; set; }
        public decimal APPITEM { get; set; }
        public decimal APPTAX1 { get; set; }
        public decimal APPTAX2 { get; set; }
        public decimal APPTAX { get; set; }
        public decimal APPAMT1 { get; set; }
        public decimal APPAMT2 { get; set; }
        public decimal APPAMT { get; set; }
        public string REM { get; set; }
        public string COMPLETE { get; set; }
        public System.DateTime COMPLETED { get; set; }
        public int SEQNO { get; set; }
        public int REFCNT { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSITEM CSITEM { get; set; }
        public virtual CSTRAND CSTRANDs { get; set; }
        public virtual CSJOBM CSJOBM { get; set; }
        public virtual CSCOMSTR CSCOMSTR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSOFF> CSOFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSOFF> CSOFFs { get; set; }
    }
}
