//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMTRCM
    {
        public string CONO { get; set; }
        public string TRNO { get; set; }
        public System.DateTime TRDATE { get; set; }
        public int FOLIONOFR { get; set; }
        public string PRSCODEFR { get; set; }
        public string EQCODEFR { get; set; }
        public string SCRIPTFR { get; set; }
        public string CERTNOFR { get; set; }
        public decimal SHAREAMT { get; set; }
        public decimal AMT { get; set; }
        public string REM { get; set; }
        public int STAMP { get; set; }
    }
}
