//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMTRSD
    {
        public string CONO { get; set; }
        public string TRNO { get; set; }
        public int TRID { get; set; }
        public string EQCODE { get; set; }
        public string SCRIPT { get; set; }
        public string CERTNO { get; set; }
        public decimal SHAREAMT { get; set; }
        public int STAMP { get; set; }
    }
}
