//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACLSD
    {
        public string CLSCODE { get; set; }
        public System.DateTime EFFDATE { get; set; }
        public string DEPMETHOD { get; set; }
        public decimal DEPRATE { get; set; }
        public string DEPTYPE { get; set; }
        public string MAPSFIX { get; set; }
        public decimal NOMINAL { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public int STAMP { get; set; }
    }
}
