//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASPLIT
    {
        public string TRNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public string ASSETNO { get; set; }
        public System.DateTime OLASTTOUCH { get; set; }
        public decimal APROV { get; set; }
        public string REM { get; set; }
        public string POST { get; set; }
        public int SEQNO { get; set; }
        public int STAMP { get; set; }
    }
}
