//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASTCHG
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public string ASSETNO { get; set; }
        public System.DateTime SDATE { get; set; }
        public System.DateTime EDATE { get; set; }
        public string CLSCODE { get; set; }
        public string DEPMETHOD { get; set; }
        public decimal DEPRATE { get; set; }
        public string DEPTYPE { get; set; }
        public decimal NOMINAL { get; set; }
        public string BRANCHCODE { get; set; }
        public string UNITCODE { get; set; }
        public string PRJCODE { get; set; }
        public string STAFFCODE { get; set; }
        public string REM { get; set; }
        public decimal BASEVAL { get; set; }
        public string POST { get; set; }
        public System.DateTime OLASTTOUCH { get; set; }
        public decimal APROV { get; set; }
        public int REFCNT { get; set; }
        public int SEQNO { get; set; }
        public int STAMP { get; set; }
    
        public virtual FACLSM FACLSM { get; set; }
        public virtual GLBRANCH GLBRANCH { get; set; }
        public virtual GLUNIT GLUNIT { get; set; }
        public virtual GLPRJ GLPRJ { get; set; }
        public virtual GLSTAFF GLSTAFF { get; set; }
    }
}
