//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCCAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PCCAT()
        {
            this.PCTRANMs = new HashSet<PCTRANM>();
        }
    
        public string CATCODE { get; set; }
        public string CATDESC { get; set; }
        public string MAPCODE { get; set; }
        public int STAMP { get; set; }
    
        public virtual HKMAP HKMAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCTRANM> PCTRANMs { get; set; }
    }
}
