//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCGLJR
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public string ENTFROM { get; set; }
        public System.DateTime ENTDATE { get; set; }
        public string CASECODE { get; set; }
        public string BRANCHCODE { get; set; }
        public string UNITCODE { get; set; }
        public string PRJCODE { get; set; }
        public string STAFFCODE { get; set; }
        public string CURRCODE { get; set; }
        public string SIGN { get; set; }
        public decimal DBAMT { get; set; }
        public decimal CRAMT { get; set; }
        public string TPOST { get; set; }
        public string GPOST { get; set; }
        public int STAMP { get; set; }
    }
}
