//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCTRANM
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public System.DateTime ENTDATE { get; set; }
        public string CLCODE { get; set; }
        public string CATCODE { get; set; }
        public string BRANCHCODE { get; set; }
        public string UNITCODE { get; set; }
        public string PRJCODE { get; set; }
        public string STAFFCODE { get; set; }
        public string CURRCODE { get; set; }
        public string PARTICULAR { get; set; }
        public string REM { get; set; }
        public string POST { get; set; }
        public string TRSIGN { get; set; }
        public decimal TRAMT { get; set; }
        public decimal TRSAMT { get; set; }
        public decimal TROS { get; set; }
        public string APPTYPE { get; set; }
        public string APPNO { get; set; }
        public Nullable<int> APPID { get; set; }
        public decimal APPAMT { get; set; }
        public string SYSGEN { get; set; }
        public string FSOURCE { get; set; }
        public string FSOURCENO { get; set; }
        public Nullable<int> FSOURCEID { get; set; }
        public int REFCNT { get; set; }
        public string COMPLETE { get; set; }
        public System.DateTime COMPLETED { get; set; }
        public int STAMP { get; set; }
    
        public virtual CICL CICL { get; set; }
        public virtual GLBRANCH GLBRANCH { get; set; }
        public virtual GLCURR GLCURR { get; set; }
        public virtual GLPRJ GLPRJ { get; set; }
        public virtual GLSTAFF GLSTAFF { get; set; }
        public virtual GLUNIT GLUNIT { get; set; }
        public virtual PCCAT PCCAT { get; set; }
    }
}
