//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAAUDITM
    {
        public string SESSIONID { get; set; }
        public string MACHINEID { get; set; }
        public string USERID { get; set; }
        public string EXUSER { get; set; }
        public System.DateTime LOGINDATE { get; set; }
        public string LOGINTIME { get; set; }
        public Nullable<System.DateTime> LOGOUTDATE { get; set; }
        public string LOGOUTTIME { get; set; }
        public string SESSIONST { get; set; }
    }
}
