//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAAUDITD
    {
        public string SESSIONID { get; set; }
        public System.DateTime ENTRYDATE { get; set; }
        public string ENTRYTIME { get; set; }
        public string PRGCODE { get; set; }
        public string ACTMODE { get; set; }
        public string CONTENT { get; set; }
    }
}
