//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACOMP
    {
        public string CONAME { get; set; }
        public string COREGNO { get; set; }
        public string COADDR1 { get; set; }
        public string COADDR2 { get; set; }
        public string COADDR3 { get; set; }
        public string COADDR4 { get; set; }
        public string COPHONE1 { get; set; }
        public string COPHONE2 { get; set; }
        public string COFAX1 { get; set; }
        public string COFAX2 { get; set; }
        public string COWEB { get; set; }
        public string CTRYOPR { get; set; }
        public string ACCMETHOD { get; set; }
        public int STAMP { get; set; }
    }
}
