//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAGRPM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAGRPM()
        {
            this.SAUSERDGs = new HashSet<SAUSERDG>();
        }
    
        public string GRPCODE { get; set; }
        public string GRPDESC { get; set; }
        public string MODULECODE { get; set; }
        public int STAMP { get; set; }
    
        public virtual SAMODULE SAMODULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAUSERDG> SAUSERDGs { get; set; }
    }
}
