//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAUSERM
    {
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string PW { get; set; }
        public System.DateTime CRDATE { get; set; }
        public short EXPDAYS { get; set; }
        public System.DateTime LUDATE { get; set; }
        public string EXUSER { get; set; }
        public short MAXSESSION { get; set; }
        public string USERTYPE { get; set; }
        public short PWMINCHAR { get; set; }
        public short PWRECYCLE { get; set; }
        public short PWFAILLOCK { get; set; }
        public string USERLOCK { get; set; }
        public int STAMP { get; set; }
    }
}
