//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSGNEWFEE
    {
        public string TRNO { get; set; }
        public string FEECODE { get; set; }
        public decimal FEEAMT { get; set; }
        public int FEEMTH { get; set; }
        public string FEETYPE { get; set; }
        public System.DateTime LASTTOUCH { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSCASE CSCASE { get; set; }
    }
}
