//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSGNEWBK
    {
        public string TRNO { get; set; }
        public string BANKCODE { get; set; }
        public string ACTYPE { get; set; }
        public string SIGNMODE { get; set; }
        public int STAMP { get; set; }
    
        public virtual HKBANK HKBANK { get; set; }
    }
}
