//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFTEMPLATE
    {
        public string CTRYOPR { get; set; }
        public string SOURCE { get; set; }
        public string DESCRIPTION { get; set; }
        public string TEMPLATE { get; set; }
        public string OUTTYPE { get; set; }
        public string OUTPROTECT { get; set; }
        public string COMM { get; set; }
        public int SEQ { get; set; }
        public int STAMP { get; set; }
    }
}
