//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SILNSCHM
    {
        public string LOANNO { get; set; }
        public int SCHID { get; set; }
        public System.DateTime EFFDATE { get; set; }
        public string REM { get; set; }
        public System.DateTime LASTTOUCH { get; set; }
        public string POST { get; set; }
        public string CFLAG { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CREM { get; set; }
        public string CPOST { get; set; }
        public int STAMP { get; set; }
    }
}
