//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SILNTRST
    {
        public string ITEM { get; set; }
        public string ITEMNO { get; set; }
        public System.DateTime ITEMDATE { get; set; }
        public string STAFFCODE { get; set; }
        public int REFCNT { get; set; }
        public string POST { get; set; }
        public int STAMP { get; set; }
    }
}
