//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SILNMSTR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SILNMSTR()
        {
            this.SILNCAPs = new HashSet<SILNCAP>();
            this.SILNCNs = new HashSet<SILNCN>();
            this.SILNDDs = new HashSet<SILNDD>();
            this.SILNINVs = new HashSet<SILNINV>();
            this.SILNWOes = new HashSet<SILNWO>();
            this.SILNWVs = new HashSet<SILNWV>();
        }
    
        public string LOANNO { get; set; }
        public System.DateTime APPDATE { get; set; }
        public string TRNO { get; set; }
        public string STAFFCODE { get; set; }
        public string LNCODE { get; set; }
        public decimal LNAMT { get; set; }
        public decimal LNOS { get; set; }
        public decimal DDAMT { get; set; }
        public string DDFULL { get; set; }
        public System.DateTime DDFULLD { get; set; }
        public string NPLFLAG { get; set; }
        public Nullable<System.DateTime> NPLDATE { get; set; }
        public string NPLREM { get; set; }
        public string NPLPOST { get; set; }
        public System.DateTime LASTTOUCH { get; set; }
        public string COMPLETE { get; set; }
        public System.DateTime COMPLETED { get; set; }
        public string CFLAG { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CREM { get; set; }
        public string CPOST { get; set; }
        public int STAMP { get; set; }
    
        public virtual SILN SILN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SILNCAP> SILNCAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SILNCN> SILNCNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SILNDD> SILNDDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SILNINV> SILNINVs { get; set; }
        public virtual SISTFST SISTFST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SILNWO> SILNWOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SILNWV> SILNWVs { get; set; }
    }
}
