//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIRATED
    {
        public string RATECODE { get; set; }
        public System.DateTime SDATE { get; set; }
        public decimal RATE { get; set; }
        public System.DateTime EDATE { get; set; }
        public int STAMP { get; set; }
    }
}
