//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTFSTLVMV
    {
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public int SOURCEID { get; set; }
        public string STAFFCODE { get; set; }
        public string FINYEAR { get; set; }
        public string LVCODE { get; set; }
        public System.DateTime MVDATE { get; set; }
        public decimal DAYSENT { get; set; }
        public decimal DAYSBF { get; set; }
        public decimal DAYSADJ { get; set; }
        public decimal DAYSEARN { get; set; }
        public decimal DAYSUTIL { get; set; }
        public decimal DAYSPEND { get; set; }
        public int SEQNO { get; set; }
        public int STAMP { get; set; }
    }
}
