//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTFSTLVADJ
    {
        public string TRNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public string STAFFCODE { get; set; }
        public string ADJCODE { get; set; }
        public string LVCODE { get; set; }
        public decimal DAYSADJ { get; set; }
        public string REM { get; set; }
        public string POST { get; set; }
        public int SEQNO { get; set; }
        public int STAMP { get; set; }
    
        public virtual SIADJ SIADJ { get; set; }
        public virtual SILV SILV { get; set; }
        public virtual SISTFST SISTFST { get; set; }
    }
}
