//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTF
    {
        public string STAFFNO { get; set; }
        public string STAFFNAME { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string NATION { get; set; }
        public string RACE { get; set; }
        public string GENDER { get; set; }
        public string MARITAL { get; set; }
        public byte[] PHOTO { get; set; }
        public string IDDNO { get; set; }
        public string EXTNO { get; set; }
        public string DIRECTNO { get; set; }
        public string MOBILENO { get; set; }
        public string EMAIL { get; set; }
        public string LOGINID { get; set; }
        public string REM { get; set; }
        public int SEQNO { get; set; }
        public string CURST { get; set; }
        public int STAMP { get; set; }
    
        public virtual HKNATION HKNATION { get; set; }
        public virtual HKRACE HKRACE { get; set; }
        public virtual HKTITLE HKTITLE { get; set; }
    }
}
