//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRSGRID
    {
        public string TRNO { get; set; }
        public int TRID { get; set; }
        public string SECAC { get; set; }
        public string IANO { get; set; }
        public string HOLDERNAME { get; set; }
        public decimal QTYHOLD { get; set; }
        public decimal QTYENTITLE { get; set; }
        public decimal QTYACCEPT { get; set; }
        public decimal EXQTYAPP { get; set; }
        public decimal EXQTYALLOT { get; set; }
        public Nullable<decimal> S1QTY { get; set; }
        public Nullable<decimal> S2QTY { get; set; }
        public Nullable<decimal> S3QTY { get; set; }
        public Nullable<decimal> S4QTY { get; set; }
        public Nullable<decimal> S5QTY { get; set; }
        public Nullable<decimal> S6QTY { get; set; }
        public Nullable<decimal> S7QTY { get; set; }
        public Nullable<decimal> S8QTY { get; set; }
        public Nullable<decimal> QTYADJ { get; set; }
        public string EXEMPTED { get; set; }
        public string SECNAME { get; set; }
        public string SRS { get; set; }
        public string REM { get; set; }
        public int STAMP { get; set; }
    }
}
