//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRSGIPODPF
    {
        public string TRNO { get; set; }
        public int TRID { get; set; }
        public string TRTYPE { get; set; }
        public string SECAC { get; set; }
        public string DACODE { get; set; }
        public string NRIC { get; set; }
        public string NATIONALITY { get; set; }
        public string SGPR { get; set; }
        public string APPNAME { get; set; }
        public string APPNAME2 { get; set; }
        public string ADDRESS { get; set; }
        public string POSTAL { get; set; }
        public string APPTYPE { get; set; }
        public decimal QTYAPPCASH { get; set; }
        public decimal QTYAPPSCHEME { get; set; }
        public string SCHEME { get; set; }
        public string BANKCODE { get; set; }
        public decimal UNITPRICE { get; set; }
        public decimal QTYALLOT { get; set; }
        public decimal S1QTY { get; set; }
        public decimal QTYADJ { get; set; }
        public string REJECT { get; set; }
        public string REJECTBY { get; set; }
        public string REJECTWHY { get; set; }
        public string REM { get; set; }
        public string REGREF { get; set; }
        public decimal CHECKSUM { get; set; }
        public string ERRORCODE { get; set; }
        public string GRPNO { get; set; }
        public string ORIGIN { get; set; }
        public int STAMP { get; set; }
    
        public virtual SRSGBANK SRSGBANK { get; set; }
        public virtual SRSGDA SRSGDA { get; set; }
    }
}
