//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRSGIPOM
    {
        public string TRNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public string CONO { get; set; }
        public decimal BFQTYAVAIL { get; set; }
        public byte[] BFS1SCRIPT { get; set; }
        public decimal PFQTYAVAIL { get; set; }
        public byte[] PFS1SCRIPT { get; set; }
        public decimal WFQTYAVAIL { get; set; }
        public byte[] WFS1SCRIPT { get; set; }
        public string SRCODE { get; set; }
        public string REM { get; set; }
        public string POST { get; set; }
        public int STAMP { get; set; }
    
        public virtual CSCOMSTR CSCOMSTR { get; set; }
        public virtual SRSGSR SRSGSR { get; set; }
    }
}
