//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRSGRIM
    {
        public string TRNO { get; set; }
        public System.DateTime VDATE { get; set; }
        public string CONO { get; set; }
        public decimal EXQTYAVAIL { get; set; }
        public byte[] S1SCRIPT { get; set; }
        public byte[] S2SCRIPT { get; set; }
        public byte[] S3SCRIPT { get; set; }
        public byte[] S4SCRIPT { get; set; }
        public byte[] S5SCRIPT { get; set; }
        public byte[] S6SCRIPT { get; set; }
        public string REM { get; set; }
        public string POST { get; set; }
        public int STAMP { get; set; }
        public byte[] S7SCRIPT { get; set; }
        public byte[] S8SCRIPT { get; set; }
    
        public virtual CSCOMSTR CSCOMSTR { get; set; }
    }
}
