//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSBFTRD
    {
        public string TRNO { get; set; }
        public int TRID { get; set; }
        public string RCPISSUER { get; set; }
        public string RCPNO { get; set; }
        public System.DateTime RCPDATE { get; set; }
        public byte[] RCPDET { get; set; }
        public decimal RCPAMT { get; set; }
        public int STAMP { get; set; }
    }
}
