//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSLNTRD
    {
        public string TRNO { get; set; }
        public int PERIODNO { get; set; }
        public decimal REPYM { get; set; }
        public string REPYMTYPE { get; set; }
        public decimal LNAMT { get; set; }
        public decimal IRATE { get; set; }
        public decimal PI { get; set; }
        public decimal PC { get; set; }
        public decimal LNOS { get; set; }
        public int STAMP { get; set; }
    }
}
