//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSLVTRDL
    {
        public string TRNO { get; set; }
        public System.DateTime LVDATE { get; set; }
        public string LVCODE { get; set; }
        public decimal LVDAY { get; set; }
        public string LVDAYTYPE { get; set; }
        public string FINYEAR { get; set; }
        public int STAMP { get; set; }
    
        public virtual SILV SILV { get; set; }
    }
}
