//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_IVTAB
    {
        public string STAFFCODE { get; set; }
        public string GROUPCODE { get; set; }
        public Nullable<int> CPOS { get; set; }
        public Nullable<int> C01 { get; set; }
        public Nullable<int> C02 { get; set; }
        public Nullable<int> C03 { get; set; }
        public Nullable<int> C04 { get; set; }
        public Nullable<int> C05 { get; set; }
        public Nullable<int> C06 { get; set; }
        public Nullable<int> C07 { get; set; }
        public Nullable<int> C08 { get; set; }
        public Nullable<int> C09 { get; set; }
        public Nullable<int> C10 { get; set; }
        public Nullable<int> C11 { get; set; }
        public Nullable<int> C12 { get; set; }
        public Nullable<int> C13 { get; set; }
        public Nullable<int> C14 { get; set; }
        public Nullable<int> C15 { get; set; }
        public Nullable<int> C16 { get; set; }
        public Nullable<int> C17 { get; set; }
        public Nullable<int> C18 { get; set; }
        public Nullable<int> STAMP { get; set; }
    }
}
