//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTEMAILSVR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UTEMAILSVR()
        {
            this.UTEMAILMs = new HashSet<UTEMAILM>();
        }
    
        public string SVRCODE { get; set; }
        public string SVRDESC { get; set; }
        public string SMTPSMTP { get; set; }
        public int SMTPPORT { get; set; }
        public string SMTPTYPE { get; set; }
        public string SMTPACC { get; set; }
        public string SMTPPW { get; set; }
        public int STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UTEMAILM> UTEMAILMs { get; set; }
    }
}
