//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTEMAILM
    {
        public string MAILID { get; set; }
        public string MAILTITLE { get; set; }
        public byte[] MAILMSG { get; set; }
        public string MAILPRIOR { get; set; }
        public string MAILRETRCP { get; set; }
        public string MAILGCODE { get; set; }
        public string SVRCODE { get; set; }
        public int STAMP { get; set; }
    
        public virtual UTEMAILGM UTEMAILGM { get; set; }
        public virtual UTEMAILSVR UTEMAILSVR { get; set; }
    }
}
