//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CSTRAN_OSTD
    {
        public string CONAME { get; set; }
        public string CONO { get; set; }
        public string COREGNO { get; set; }
        public Nullable<System.DateTime> ENTDATE { get; set; }
        public string PARTICULARS { get; set; }
        public string PARTICULARS1 { get; set; }
        public string PARTICULARS2 { get; set; }
        public string SOURCE { get; set; }
        public string SOURCENO { get; set; }
        public decimal TRAMT { get; set; }
        public decimal TROS { get; set; }
        public decimal MINAMT { get; set; }
        public decimal MAXAMT { get; set; }
    }
}
