//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CSCOAR
    {
        public string CONAME { get; set; }
        public string CONO { get; set; }
        public string COREGNO { get; set; }
        public Nullable<short> ARNO { get; set; }
        public Nullable<System.DateTime> LASTAR { get; set; }
        public Nullable<System.DateTime> ARTOFILE { get; set; }
        public Nullable<System.DateTime> FILEDAR { get; set; }
        public Nullable<System.DateTime> REMINDER1 { get; set; }
        public string REM { get; set; }
        public Nullable<int> STAMP { get; set; }
        public Nullable<System.DateTime> SUBMITAR { get; set; }
        public string REMINDER2 { get; set; }
        public Nullable<short> REMTH1 { get; set; }
        public string REMINDERTYPE { get; set; }
        public string STAFFCODE { get; set; }
        public string STAFFDESC { get; set; }
    }
}
